### ISSUE TITLE
fix transaction errors for integration tests

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize-dbt-utils#11]
A user reported that the integration tests for `materialize-dbt-utils` are failing due to transaction errors. Given a screenshot of the errors, it seems like the issue is similar to what we [saw here](https://github.com/MaterializeInc/materialize/pull/6525). We should:
1. Fix the transaction errors caused by the macros in this repository
2. Add the integration tests from this repository into our main repository's [test pipeline](https://github.com/MaterializeInc/materialize/blob/main/ci/test/pipeline.template.yml) to ensure this doesn't happen again in the future

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/commit/7772735cc20c566cf7f0ce77126eaba454002926.
