### ISSUE TITLE
Enable remaining macros

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize-dbt-utils#17]
Once #15 lands, only the following macros will remain unimplemented:

  * [x] Requires support for creating views with `current_timestamp`:
    * `recency`
    * `current_timestamp`
  * [ ] Requires support for the `lag` window function:
    * `sequential_values`
  * [ ] Requires support for the `lead` window function:
    * `mutually_exclusive_ranges`

**Comment by benesch** [comment]
`recency` and `current_timestamp` are done now. Just `lead` and `lag` remain.

**Comment by morsapaes** [comment]
`lead` and `lag` are now implemented, so if they're released in `v0.26.1` we can enable the remaining macros and close this issue.
